import {
  Anvil,
  Armchair,
  Blocks,
  BookMarked,
  BookOpen,
  Boxes,
  Calculator,
  CloudRain,
  Compass,
  Cookie,
  Droplets,
  Drum,
  Factory,
  Feather,
  Flame,
  Footprints,
  Gauge,
  GraduationCap,
  Grid3x3,
  HardHat,
  Images,
  Lamp,
  Layers,
  Leaf,
  Lightbulb,
  ListOrdered,
  Map as MapIcon,
  Moon,
  Palette,
  PieChart,
  Rabbit,
  Rainbow,
  Ruler,
  Scale,
  Scroll,
  Shapes,
  Snowflake,
  Sparkles,
  StickyNote,
  Sun,
  Sunrise,
  Telescope,
  Train,
  Umbrella,
  Wind,
} from "lucide-react";
import type { Reward } from "./types";

const INDUSTRIAL: Reward[] = [
  {
    id: "rw_ir_spindle",
    name: "Cottage Spindle",
    blurb: "The hand tool that did the job before any machine did.",
    slot: "held",
    icon: Feather,
    tone: "ray1",
    subjectSlug: "industrial-revolution",
    trigger: { kind: "chapter", subjectSlug: "industrial-revolution", chapterOrder: 1 },
  },
  {
    id: "rw_ir_engine",
    name: "Beam Engine",
    blurb: "Watt's condenser, the part that let factories leave the riverbank.",
    slot: "shelf",
    icon: Gauge,
    tone: "ray2",
    subjectSlug: "industrial-revolution",
    trigger: { kind: "chapter", subjectSlug: "industrial-revolution", chapterOrder: 2 },
  },
  {
    id: "rw_ir_lamp",
    name: "Inspector's Lamp",
    blurb: "For reading the record of what actually happened on a mill floor.",
    slot: "held",
    icon: Lamp,
    tone: "ray4",
    subjectSlug: "industrial-revolution",
    trigger: { kind: "chapter", subjectSlug: "industrial-revolution", chapterOrder: 3 },
  },
  {
    id: "rw_ir_rain",
    name: "Manchester Sky",
    blurb: "Smoke, rain and rooftops. Not pretty. Accurate.",
    slot: "backdrop",
    icon: CloudRain,
    tone: "brand",
    subjectSlug: "industrial-revolution",
    trigger: { kind: "chapter", subjectSlug: "industrial-revolution", chapterOrder: 4 },
  },
  {
    id: "rw_ir_scroll",
    name: "Reform Bill",
    blurb: "Evidence, gathered and written down, is how the law changed.",
    slot: "wall",
    icon: Scroll,
    tone: "ray3",
    subjectSlug: "industrial-revolution",
    trigger: { kind: "chapter", subjectSlug: "industrial-revolution", chapterOrder: 5 },
  },
  {
    id: "rw_ir_globe",
    name: "Cotton Routes",
    blurb: "Where the cotton came from, and what that cost.",
    slot: "wall",
    icon: MapIcon,
    tone: "ray2",
    subjectSlug: "industrial-revolution",
    trigger: { kind: "chapter", subjectSlug: "industrial-revolution", chapterOrder: 6 },
  },
  {
    id: "rw_ir_mill",
    name: "Cromford Mill",
    blurb: "The whole course, start to finish. This one is hard to get.",
    slot: "backdrop",
    icon: Factory,
    tone: "lumen",
    subjectSlug: "industrial-revolution",
    trigger: { kind: "subject_complete", subjectSlug: "industrial-revolution" },
  },
  {
    id: "rw_ir_hat",
    name: "Mill Hand's Cap",
    blurb: "Worn by the people this course is actually about.",
    slot: "hat",
    icon: HardHat,
    tone: "ray1",
    subjectSlug: "industrial-revolution",
    trigger: { kind: "chapter", subjectSlug: "industrial-revolution", chapterOrder: 3 },
  },
  {
    id: "rw_ir_train",
    name: "Rocket",
    blurb: "Liverpool to Manchester, 1830. Everything got closer together.",
    slot: "shelf",
    icon: Train,
    tone: "ray3",
    subjectSlug: "industrial-revolution",
    trigger: { kind: "chapter", subjectSlug: "industrial-revolution", chapterOrder: 2 },
  },
  {
    id: "rw_ir_anvil",
    name: "Iron Anvil",
    blurb: "Nothing in this course gets built without it.",
    slot: "floor",
    icon: Anvil,
    tone: "ray1",
    subjectSlug: "industrial-revolution",
    trigger: { kind: "chapter", subjectSlug: "industrial-revolution", chapterOrder: 5 },
  },
];

const MATHS: Reward[] = [
  {
    id: "rw_math_pie",
    name: "Fraction Wheel",
    blurb: "Turn it and the same whole splits a different way.",
    slot: "held",
    icon: PieChart,
    tone: "ray3",
    subjectSlug: "math-g4",
    trigger: { kind: "chapter", subjectSlug: "math-g4", chapterOrder: 1 },
  },
  {
    id: "rw_math_scale",
    name: "Balance Scale",
    blurb: "Fair shares, proved rather than argued about.",
    slot: "shelf",
    icon: Scale,
    tone: "ray2",
    subjectSlug: "math-g4",
    trigger: { kind: "chapter", subjectSlug: "math-g4", chapterOrder: 2 },
  },
  {
    id: "rw_math_ruler",
    name: "Folding Ruler",
    blurb: "Halves, quarters, eighths — all on one stick.",
    slot: "held",
    icon: Ruler,
    tone: "ray4",
    subjectSlug: "math-g4",
    trigger: { kind: "chapter", subjectSlug: "math-g4", chapterOrder: 3 },
  },
  {
    id: "rw_math_shapes",
    name: "Tiling Set",
    blurb: "Every course chapter done. The shapes fit exactly.",
    slot: "floor",
    icon: Shapes,
    tone: "lumen",
    subjectSlug: "math-g4",
    trigger: { kind: "subject_complete", subjectSlug: "math-g4" },
  },
];

const SCIENCE: Reward[] = [
  {
    id: "rw_sci_droplet",
    name: "Water Cycle Jar",
    blurb: "It rains inside. Small enough to keep on a shelf.",
    slot: "shelf",
    icon: Droplets,
    tone: "ray2",
    subjectSlug: "science-g4",
    trigger: { kind: "chapter", subjectSlug: "science-g4", chapterOrder: 1 },
  },
  {
    id: "rw_sci_wind",
    name: "Wind Vane",
    blurb: "Points where the weather is coming from, not where it's been.",
    slot: "wall",
    icon: Wind,
    tone: "ray1",
    subjectSlug: "science-g4",
    trigger: { kind: "chapter", subjectSlug: "science-g4", chapterOrder: 2 },
  },
  {
    id: "rw_sci_leaf",
    name: "Pressed Fern",
    blurb: "Field notes, kept.",
    slot: "wall",
    icon: Leaf,
    tone: "ray3",
    subjectSlug: "science-g4",
    trigger: { kind: "chapter", subjectSlug: "science-g4", chapterOrder: 3 },
  },
  {
    id: "rw_sci_telescope",
    name: "Brass Telescope",
    blurb: "The whole of Weather and Water. Now look further up.",
    slot: "shelf",
    icon: Telescope,
    tone: "lumen",
    subjectSlug: "science-g4",
    trigger: { kind: "subject_complete", subjectSlug: "science-g4" },
  },
];

const READING: Reward[] = [
  {
    id: "rw_read_book",
    name: "Margin Notes",
    blurb: "A book somebody argued with in pencil.",
    slot: "held",
    icon: BookOpen,
    tone: "ray1",
    subjectSlug: "reading-g4",
    trigger: { kind: "chapter", subjectSlug: "reading-g4", chapterOrder: 1 },
  },
  {
    id: "rw_read_compass",
    name: "Reader's Compass",
    blurb: "For working out where a writer is actually taking you.",
    slot: "held",
    icon: Compass,
    tone: "ray4",
    subjectSlug: "reading-g4",
    trigger: { kind: "chapter", subjectSlug: "reading-g4", chapterOrder: 2 },
  },
  {
    id: "rw_read_lamp",
    name: "Reading Lamp",
    blurb: "Stays on as long as you want it to.",
    slot: "floor",
    icon: Lightbulb,
    tone: "ray3",
    subjectSlug: "reading-g4",
    trigger: { kind: "chapter", subjectSlug: "reading-g4", chapterOrder: 3 },
  },
];

const LETTERS: Reward[] = [
  {
    id: "rw_let_blocks",
    name: "Alphabet Blocks",
    blurb: "All 26 letters, in a pile you can stack.",
    slot: "shelf",
    icon: Blocks,
    tone: "ray1",
    subjectSlug: "letters-k",
    trigger: { kind: "chapter", subjectSlug: "letters-k", chapterOrder: 1 },
  },
  {
    id: "rw_let_cards",
    name: "Picture Cards",
    blurb: "Sun, sock, snake. Say them out loud and listen to the front.",
    slot: "held",
    icon: Images,
    tone: "ray2",
    subjectSlug: "letters-k",
    trigger: { kind: "chapter", subjectSlug: "letters-k", chapterOrder: 2 },
  },
  {
    id: "rw_let_drum",
    name: "Rhyme Drum",
    blurb: "Cat, hat, bat. One beat each.",
    slot: "held",
    icon: Drum,
    tone: "ray3",
    subjectSlug: "letters-k",
    trigger: { kind: "chapter", subjectSlug: "letters-k", chapterOrder: 3 },
  },
  {
    id: "rw_let_mat",
    name: "Reading Mat",
    blurb: "Somewhere to sit and sound a word out slowly.",
    slot: "floor",
    icon: BookOpen,
    tone: "ray4",
    subjectSlug: "letters-k",
    trigger: { kind: "chapter", subjectSlug: "letters-k", chapterOrder: 4 },
  },
  {
    id: "rw_let_wordwall",
    name: "Word Wall",
    blurb: "The, and, I, see, go. The words that turn up everywhere.",
    slot: "wall",
    icon: StickyNote,
    tone: "ray1",
    subjectSlug: "letters-k",
    trigger: { kind: "chapter", subjectSlug: "letters-k", chapterOrder: 5 },
  },
  {
    id: "rw_let_reader",
    name: "First Reader",
    blurb: "A whole book, read by you. Every chapter of the course is done.",
    slot: "shelf",
    icon: BookMarked,
    tone: "lumen",
    subjectSlug: "letters-k",
    trigger: { kind: "subject_complete", subjectSlug: "letters-k" },
  },
];

const COUNTING: Reward[] = [
  {
    id: "rw_cnt_bears",
    name: "Counting Bears",
    blurb: "Ten of them. Line them up and touch each one as you count.",
    slot: "shelf",
    icon: Cookie,
    tone: "ray3",
    subjectSlug: "counting-k",
    trigger: { kind: "chapter", subjectSlug: "counting-k", chapterOrder: 1 },
  },
  {
    id: "rw_cnt_line",
    name: "Number Line",
    blurb: "1 to 20, in order, right along the wall.",
    slot: "wall",
    icon: ListOrdered,
    tone: "ray2",
    subjectSlug: "counting-k",
    trigger: { kind: "chapter", subjectSlug: "counting-k", chapterOrder: 2 },
  },
  {
    id: "rw_cnt_frame",
    name: "Ten Frame",
    blurb: "Ten little boxes. Fill them and you can see ten without counting.",
    slot: "floor",
    icon: Grid3x3,
    tone: "ray4",
    subjectSlug: "counting-k",
    trigger: { kind: "chapter", subjectSlug: "counting-k", chapterOrder: 3 },
  },
  {
    id: "rw_cnt_jar",
    name: "Counting Jar",
    blurb: "Every chapter counted out. Nothing left in the jar.",
    slot: "shelf",
    icon: Calculator,
    tone: "lumen",
    subjectSlug: "counting-k",
    trigger: { kind: "subject_complete", subjectSlug: "counting-k" },
  },
];

const SHAPES_COLORS: Reward[] = [
  {
    id: "rw_shp_sorter",
    name: "Shape Sorter",
    blurb: "Circle, square, triangle. Each one only fits one hole.",
    slot: "floor",
    icon: Shapes,
    tone: "ray1",
    subjectSlug: "shapes-k",
    trigger: { kind: "chapter", subjectSlug: "shapes-k", chapterOrder: 1 },
  },
  {
    id: "rw_shp_paints",
    name: "Paint Pots",
    blurb: "Red and yellow make orange. Try it and see.",
    slot: "shelf",
    icon: Palette,
    tone: "ray2",
    subjectSlug: "shapes-k",
    trigger: { kind: "chapter", subjectSlug: "shapes-k", chapterOrder: 2 },
  },
  {
    id: "rw_shp_rainbow",
    name: "Rainbow",
    blurb: "Every colour, in the order they always come in.",
    slot: "backdrop",
    icon: Rainbow,
    tone: "lumen",
    subjectSlug: "shapes-k",
    trigger: { kind: "subject_complete", subjectSlug: "shapes-k" },
  },
];

const WEATHER_K: Reward[] = [
  {
    id: "rw_wth_boots",
    name: "Rain Boots",
    blurb: "For the puddles. Sized for jumping in.",
    slot: "floor",
    icon: Umbrella,
    tone: "ray2",
    subjectSlug: "weather-k",
    trigger: { kind: "chapter", subjectSlug: "weather-k", chapterOrder: 1 },
  },
  {
    id: "rw_wth_suncatcher",
    name: "Sun Catcher",
    blurb: "Hang it up and it throws colours on the floor.",
    slot: "wall",
    icon: Sun,
    tone: "ray1",
    subjectSlug: "weather-k",
    trigger: { kind: "chapter", subjectSlug: "weather-k", chapterOrder: 2 },
  },
  {
    id: "rw_wth_globe",
    name: "Snow Globe",
    blurb: "Shake it and winter happens in your hand.",
    slot: "shelf",
    icon: Snowflake,
    tone: "ray3",
    subjectSlug: "weather-k",
    trigger: { kind: "chapter", subjectSlug: "weather-k", chapterOrder: 3 },
  },
];

const HABITS: Reward[] = [
  {
    id: "rw_habit_secondlook",
    name: "Second Look",
    blurb:
      "For going back to a quiz that didn't go well the first time. That's the hard one.",
    slot: "badge",
    icon: Layers,
    tone: "ray4",
    trigger: { kind: "quiz_retry" },
  },
  {
    id: "rw_habit_return",
    name: "Back Again",
    blurb: "You'd been away a while. You came back. That counts for something.",
    slot: "badge",
    icon: Sunrise,
    tone: "ray3",
    trigger: { kind: "return_after_absence", days: 7 },
  },
  {
    id: "rw_habit_thorough",
    name: "Every Question",
    blurb: "Five lessons where you answered every practice question on the way through.",
    slot: "badge",
    icon: Footprints,
    tone: "ray2",
    trigger: { kind: "lesson_thorough", count: 5 },
  },
  {
    id: "rw_habit_weeks",
    name: "Four Good Weeks",
    blurb: "Four separate weeks with three study days in them. Not in a row — just four.",
    slot: "aura",
    icon: Flame,
    tone: "ray1",
    trigger: { kind: "active_weeks", count: 4 },
  },
  {
    id: "rw_habit_radiant",
    name: "Still Knew It",
    blurb: "You passed something again a week later, without going back over it first.",
    slot: "aura",
    icon: Sparkles,
    tone: "ray3",
    trigger: { kind: "mastery", tier: "radiant" },
  },
  {
    id: "rw_habit_prism",
    name: "A Month On",
    blurb: "A whole month later and it was still there. This is the rarest thing here.",
    slot: "aura",
    icon: Moon,
    tone: "lumen",
    trigger: { kind: "mastery", tier: "prism" },
  },
  {
    id: "rw_habit_five",
    name: "Five Chapters",
    blurb: "Five finished, across any of your courses.",
    slot: "badge",
    icon: Boxes,
    tone: "ray1",
    trigger: { kind: "chapters_total", count: 5 },
  },
  {
    id: "rw_habit_ten",
    name: "Ten Chapters",
    blurb: "Ten finished. Look back at where you started.",
    slot: "hat",
    icon: GraduationCap,
    tone: "ray2",
    trigger: { kind: "chapters_total", count: 10 },
  },
];

const FURNISHING: Reward[] = [
  {
    id: "rw_room_chair",
    name: "Reading Chair",
    blurb: "Somewhere to actually sit.",
    slot: "floor",
    icon: Armchair,
    tone: "ray2",
    trigger: { kind: "chapters_total", count: 2 },
  },
  {
    id: "rw_room_dawn",
    name: "Morning Window",
    blurb: "Light coming in from outside.",
    slot: "backdrop",
    icon: Sunrise,
    tone: "ray3",
    trigger: { kind: "chapters_total", count: 3 },
  },
  {
    id: "rw_room_rabbit",
    name: "Wren",
    blurb:
      "Lives here now. Doesn't need feeding, won't get sad if you're away — she just likes the company.",
    slot: "pet",
    icon: Rabbit,
    tone: "ray4",
    trigger: { kind: "active_weeks", count: 2 },
  },
];

export const CATALOG: Reward[] = [
  ...INDUSTRIAL,
  ...MATHS,
  ...SCIENCE,
  ...READING,
  ...LETTERS,
  ...COUNTING,
  ...SHAPES_COLORS,
  ...WEATHER_K,
  ...HABITS,
  ...FURNISHING,
];

export const REWARDS_BY_ID = new Map(CATALOG.map((reward) => [reward.id, reward]));

export function rewardById(id: string): Reward | undefined {
  return REWARDS_BY_ID.get(id);
}

export const TONE_VAR: Record<Reward["tone"], string> = {
  brand: "var(--color-brand)",
  ray1: "var(--color-ray-1)",
  ray2: "var(--color-ray-2)",
  ray3: "var(--color-ray-3)",
  ray4: "var(--color-ray-4)",
  lumen: "var(--color-lumen)",
};
