/* Writes export SVG + Lottie-fit SVG + TS module for LottieBuddy. */
const fs = require('fs');
const path = require('path');
const { buildHairSVG, buildHairLayers, LOTTIE_HAIR_FIT } = require('./hair.js');

const here = __dirname;
fs.writeFileSync(path.join(here, 'hair.svg'), buildHairSVG({ glow: true }));
fs.writeFileSync(path.join(here, 'hair-no-bg.svg'), buildHairSVG({ glow: false }));
fs.writeFileSync(
  path.join(here, 'hair-lottie.svg'),
  buildHairSVG({ format: 'lottie', glow: false }),
);

const layers = buildHairLayers();
const ts = `/* Auto-generated by design-exports/hair/export-svg.js — do not hand-edit.
 * Soft bob fitted to LottieBuddy 100×100.
 * Groups: Back Cap, Left Lock, Right Lock, Shadows, Front Bangs, Highlights
 * Face opening design: x ${LOTTIE_HAIR_FIT.faceL}–${LOTTIE_HAIR_FIT.faceR}, brow y ${LOTTIE_HAIR_FIT.browY}
 */
export const LOTTIE_HAIR_FIT = ${JSON.stringify(layers.fit, null, 2)} as const;

export interface SoftBobShadow {
  d: string;
  opacity: number;
}

export const SOFT_BOB_LAYERS = {
  backCap: ${JSON.stringify(layers.backCap)},
  leftLock: ${JSON.stringify(layers.leftLock)},
  rightLock: ${JSON.stringify(layers.rightLock)},
  shadows: ${JSON.stringify(layers.shadows)} as SoftBobShadow[],
  bounceLight: ${JSON.stringify(layers.bounceLight)},
  frontBangs: ${JSON.stringify(layers.frontBangs)},
  highlights: ${JSON.stringify(layers.highlights)},
} as const;
`;

const outTs = path.join(here, '../../components/domain/hair/softBobPaths.ts');
fs.mkdirSync(path.dirname(outTs), { recursive: true });
fs.writeFileSync(outTs, ts);

console.log('wrote hair.svg, hair-no-bg.svg, hair-lottie.svg');
console.log('wrote', path.relative(here, outTs));
